defmodule Twitter.Repo.Migrations.AddTweetVectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tweets) do
      add :full_text_vector, :vector, size: 1536
    end

    create index(:tweets, ["full_text_vector vector_cosine_ops"],
             name: "tweets_full_text_vector_index",
             using: "hnsw"
           )
  end

  def down do
    drop_if_exists index(:tweets, ["full_text_vector vector_cosine_ops"],
                     name: "tweets_full_text_vector_index"
                   )

    alter table(:tweets) do
      remove :full_text_vector
    end
  end
end
